export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_SLIDE = "FETCH_SLIDE";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_ALL = "FETCH_PRODUCT_ALL";
export const LOADMORE = "LOADMORE";